### ISSUE TITLE
 Unable to find a specification for pod

### ISSUE THREAD

**Issue by n1schal** [ahmedAlmasri/SNCollectionViewLayout#1]
Added pod 'SNCollectionViewLayout' and then hit pod install from my project directory and this is what I get :

[!] Unable to find a specification for `SNCollectionViewLayout`

**Comment by ahmedAlmasri** [comment]
What is the pod version?
what is minimum deployment target in your project?

**Comment by ahmedAlmasri** [comment]
check this requirements  https://github.com/ahmedAlmasri/SNCollectionViewLayout#requirements
