### ISSUE TITLE
customize layout by section

### ISSUE THREAD

**Issue by mmdock** [ahmedAlmasri/SNCollectionViewLayout#2]
I would like to have my first section look something like 

<img width="339" alt="Screen Shot 2019-05-06 at 11 13 37 AM" src="https://user-images.githubusercontent.com/2423465/57245574-0fd59300-6ff0-11e9-85a9-052cff77f385.png">

but then i would like the subsequent sections to looks more like a normal cell where the width is the length of the collection view, but have a smaller height.  

Something more like: 
<img width="184" alt="Screen Shot 2019-05-06 at 11 15 13 AM" src="https://user-images.githubusercontent.com/2423465/57245705-56c38880-6ff0-11e9-8be6-370eaa3af67c.png">

How could I use the SNCollectionViewLayout to achieve this ?

**Comment by ahmedAlmasri** [comment]
Hello @mmdock 

you are must change CollectionViewLayout for section 
read it 

[stackoverflow-53605022](https://stackoverflow.com/questions/53605022/changing-uicollectionview-layout-depending-on-section)

**Comment by mmdock** [comment]
@ahmedAlmasri when i try to do that while also using your SNCollectionVIewLayout, my changes for other sections seem to be ignored.
