### ISSUE TITLE
Deplyment Target issue

### ISSUE THREAD

**Issue by OmarIbbu** [ahmedAlmasri/SNCollectionViewLayout#3]
I want to deploy it on minimum target 10.0 which is not supported by this library. Is it possible?

**Comment by ahmedAlmasri** [comment]
Hi @OmarIbbu 

try to use : `pod 'SNCollectionViewLayout', :git =>  https://github.com/ahmedAlmasri/SNCollectionViewLayout.git :branch => 'ios_10'`
